config/routes.rb
GAL::Application.routes.draw do
  resources :sachse_groups
  get "welcome/index"
  resources :jobs do
    resources :checkbooks
    resources :job_assignments
    resources :staff_assignments
    resources :dailys do
      resources :daily_notes
    end
  end
  resources :psr
  resources :contract_types
  resources :states
  resources :project_types
  resources :project_phases
  resources :companies do
    resources :contacts
  end
  devise_for :users
  root to: 'welcome#index'
end

app/models/checkbook.rb
class Checkbook < ActiveRecord::Base
  belongs_to :job
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :state
  belongs_to :company_type
  belongs_to :trade
  belongs_to :country
  
  has_many :specialties
  has_many :trades, through: :specialties
  has_many :employments
  has_many :contacts, through: :employments

  has_many :job_assignments
  has_many :jobs, through: :job_assignments
  has_many :daily_manpowers, through: :job_assignments
end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
  has_many :companies
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :company_department
  belongs_to :state
  belongs_to :country

  has_many :employments
  has_many :companies, through: :employments

  has_many :job_assignments
  has_many :jobs, through: :job_assignments
  has_many :daily_manpowers, through: :job_assignments
end

app/models/contract_type.rb
class ContractType < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :companies
end

app/models/daily.rb
class Daily < ActiveRecord::Base
  belongs_to :job
  belongs_to :user
  has_many :daily_notes
  has_many :daily_manpowers
  has_many :contacts, through: :job_assignments
  has_many :daily_equipments
end

app/models/daily_note.rb
class DailyNote < ActiveRecord::Base
  belongs_to :daily
end

app/models/employment.rb
class Employment < ActiveRecord::Base
  belongs_to :company
  belongs_to :contact

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :state
  belongs_to :country
  belongs_to :project_phase
  belongs_to :project_type
  belongs_to :sachse_group
  belongs_to :union
  belongs_to :contract_type

  accepts_nested_attributes_for :state

  has_many :staff_assignments
  has_many :project_roles, through: :staff_assignments

  has_many :job_assignments
  has_many :companies, through: :job_assignments
  has_many :contacts, through: :job_assignments

  has_many :checkbooks

  has_many :dailys

  validates :name, presence: true

  before_save :assign_job_number, on: [ :create, :update ]
  before_save :change_job_number, on: [ :update ]
  before_save :assign_precon_number, on: :create


  def superintendents
    array = []
    self.staff_assignments.each do |staff|
      array << staff.user.name if staff.project_role.name == "Superintendent"
    end
    array
  end

  protected



  def assign_precon_number
    if !self.precon_number?
      array = []
        j = Job.all
        j.each do |job|
            #Loop across all jobs and pull out those that have a job number, as well as check if the first two digits of that job number (the year) == the current year
            array << job.precon_number if job.precon_number? && Time.now.strftime("%y") == job.precon_number[0..1]
          end
          #add one to the count of the array (if the current year and job number year don't equal, then it must be a new year and the count starts at 0)
          a = array.count + 1
      y = Time.now.strftime("%y")
      t = 35
      c = a.to_s.rjust(3, '0')
      self.precon_number = "#{y}-#{t}-#{c}"
      
    end
  end

  def assign_job_number


    #Does the job not have a job # but have a Contract Type?
    if !self.number? && self.contract_type_id?
        #Create an empty array
        array = []
        j = Job.all
        j.each do |job|
          #Loop across all jobs and pull out those that have a job number, and also check to see if the job number's year == the current year
          array << job.number if job.number? && Time.now.strftime("%y") == job.number[0..1]
        end
        a = array.count + 1
        y = Time.now.strftime("%y")
        t = self.contract_type.number
        c = a.to_s.rjust(3, '0')
        self.number = "#{y}-#{t}-#{c}"
    end
  end

  def change_job_number
    #Check if the job has a contract ID
    if self.contract_type_id?
      n = self.number
      y = n[0..1]
      t = self.contract_type.number
      c = n[6..8]
      self.number = "#{y}-#{t}-#{c}"
    end
  end
end

app/models/project_role.rb
class ProjectRole < ActiveRecord::Base
  has_many :staff_assignments
  has_many :jobs, through: :staff_assignments

  has_many :role_assignments
  has_many :users, through: :role_assignments

end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
end

app/models/sachse_group.rb
class SachseGroup < ActiveRecord::Base
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  belongs_to :company
  belongs_to :trade
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :companies
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  has_many :specialties
  has_many :companies, through: :specialties
end

app/models/union.rb
class Union < ActiveRecord::Base
  has_many :companies
  has_many :jobs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :role_assignments
  has_many :project_roles, through: :role_assignments
  has_many :dailys



  def name
    if self.l_name
      self.f_name + " " + self.l_name
    else
      self.f_name
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  include NavHelper
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html
      format.json { render json: @jobs, root: false }
    end
  end

  def new
    @job = Job.new
  end

  def show
    @job = Job.find(params[:id])
    @companies = @job.companies
    @staff_assignments = @job.staff_assignments
    @new_staff_assignment = StaffAssignment.new
    @job_assignment = JobAssignment.new
    @checkbook = Checkbook.new
    @checkbooks = @job.checkbooks
    # binding.pry
    @nav_list_items = job_nav_list_items
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    #binding.pry
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, root: false, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end


  def update
   @job = Job.find(params[:id])


    #"jobs#update"
    #binding.pry
    case params[:job][:update_type]
    when :assign_job_number
      @job.assign_job_number!
    else
      # behavor normally
      respond_to do |format|
        if @job.update_attributes(job_params)
          format.html { redirect_to @job, notice: 'Job was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @job.errors, root: true,status: :unprocessable_entity }
        end
      end
    end
  end



  private

  def job_params
    params.require(:job).permit(:state_id, :name, :number, :precon_number, :address, :city, :zip, :country_id, :project_phase_id, :project_type_id, :sachse_group_id, :contract_type_id, :sqft, :start_date, :turnover_date, :building)
  end
end

app/helpers/daily_helper.rb
module DailyHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/nav_helper.rb
module NavHelper
  def job_nav_list_items
    # @job = Job.find(params[:id])
    @nav_list_items = [[job_checkbooks_path(@job), 'Checkbooks'], [job_dailys_path(@job), "Daily Logs"]]
  end
end

app/helpers/psr_helper.rb
module PsrHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job, html: {class: "smart-form"} do |f| %>
    <header>
      Standard Form Header
    </header>

    <fieldset>
      
      <section>
        <%= f.label :name, class: 'label' %>
        <label class="input">
          <%= f.text_field :name, class: 'input-xs' %>
        </label>
      </section>

       <section>
        <%= f.label :address, class: 'label' %>
        <label class="input">
          <%= f.text_field :address, class: 'input-xs' %>
        </label>
      </section>

      <section>
        <%= f.label :city, class: 'label' %>
        <label class="input">
          <%= f.text_field :city, class: 'input-xs' %>
        </label>
      </section>
                      
    <section>
        <%= f.label :zip, class: 'label' %>
        <label class="input">
          <%= f.text_field :zip, class: 'input-xs' %>
        </label>
      </section>

    
    </fieldset>
    
    <footer>
    <%= f.submit "Save", class: 'btn btn-primary' %>
      <button type="button" class="btn btn-default" onclick="window.history.back();">
        Back
      </button>
    </footer>
  <% end %>

app/views/jobs/edit.html.erb
          <div class="row">
            <article class="col-sm-12 col-md-12 col-lg-6">
              <div class="jarviswidget" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                <header>
                  <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
                  <h2>Edit Job </h2>
                </header>
                <div>
                  <div class="jarviswidget-editbox">
                  </div>
                  <div class="widget-body no-padding">
                    <%= render partial: 'form', locals: { job: @job } %>
                  </div>
               </div>
              </div>
            </article>
          </div>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<div class="row">
  <div class="col-md-8">
    <% @jobs.each do |job| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to job.name, job %>
          </h4>
          <small>
            <%= job.number %><br>
            <%= job.city %>, <%= job.state.name if job.state %> <%= job.zip %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
      <%= link_to "New Job", new_job_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/jobs/new.html.erb
          <div class="row">
            <article class="col-sm-12 col-md-12 col-lg-6">
              <div class="jarviswidget" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                <header>
                  <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
                  <h2>New Job </h2>
                </header>
                <div>
                  <div class="jarviswidget-editbox">
                  </div>
                  <div class="widget-body no-padding">
                    <%= render partial: 'form', locals: { job: @job } %>
                  </div>
               </div>
              </div>
            </article>
          </div>

app/views/jobs/show.html.erb
<h2><%= @job.name %></h2>
<div class="row">
  <div class="col-sm-3">
    <h5>Job #:<%= @job.number %></h5>
  </div>
  <div class="col-sm-3">
    <h5>Precon #:<%= @job.precon_number %></h5>
  </div>
</div>

<div class="row">

  <article class="col-sm-12 col-md-12 col-lg-6">

    <div class="jarviswidget well" id="wid-id-3" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false" data-widget-sortable="false">

      <header>
        <span class="widget-icon"> <i class="fa fa-comments"></i> </span>
        <h2>Default Tabs with border </h2>

      </header>

      <div>

        <!-- widget edit box -->
        <div class="jarviswidget-editbox">
          <!-- This area used as dropdown edit box -->

        </div>
        <!-- end widget edit box -->

        <!-- widget content -->
        <div class="widget-body">

          <hr class="simple">
          <ul id="myTab1" class="nav nav-tabs bordered">
            <li class="active">
              <a href="#s1" data-toggle="tab">Job Data</a>
            </li>
            <li>
              <a href="#s2" data-toggle="tab"><i class="fa fa-fw fa-lg fa-gear"></i> Job Contacts</a>
            </li>
            <li>
              <a href="#s3" data-toggle="tab"><i class="fa fa-fw fa-lg fa-gear"></i> Job Staff</a>
            </li>
            <li>
              <a href="#s4" data-toggle="tab"></i> Checkbooks</a>
            </li>
          </ul>

          <div id="myTabContent1" class="tab-content padding-10">
            <div class="tab-pane fade in active" id="s1">
              <b>Building:</b> <%= @job.building %>
            </div>
            <div class="tab-pane fade" id="s2">
              <table id='job-contacts' class='table table-bordered table-striped'>
                <thead>
                <tr>
                  <th>Type</th>
                  <th>Company</th>
                  <th>Address</th>
                  <th>Contact</th>
                </tr>
              </thead>
              <tbody>
                <% @companies.each do |company| %> 
                <tr>
                  <td><%= company.company_type.name rescue "this is bad form" %></td>
                  <td><%= link_to company.name, company rescue "this is bad form" %></td>
                  <td><%= company.address %></td>
                  <td>Test</td>
                </tr>
                <% end %>
              </tbody>
              </table>
              <%= form_for [@job, @job_assignment] do |f| %>
                <%= f.collection_select :company_id, Company.all, :id, :name %>
                <%= f.hidden_field :job_id, value: @job.id %>
                <%= f.submit %>
              <% end %>
            </div>
            <div class="tab-pane fade" id="s3">
              <table id='staff-contacts' class='table table-bordered table-striped'>
                <thead>
                <tr>
                  <th>Project Role</th>
                  <th>Name</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @staff_assignments.each do |assignment| %> 
                <tr id='staff_assignment_<%=assignment.id %>'>
                  <td><%= assignment.project_role.name %></td>
                  <td><%= assignment.user.name rescue "bad"%></td>
                  <td><%= link_to 'Destroy', job_staff_assignment_path(assignment.job, assignment), :method => :delete, :class => 'btn btn-mini btn-danger', remote: true %></td>
                </tr>
                <% end %>
              </tbody>
              </table>
               <%= form_for [@job, @new_staff_assignment], remote: true, authenticity_token: true do |f| %>
                  <%= f.collection_select :project_role_id, ProjectRole.order(:name), :id, :name, include_blank: true %>
                  <%= f.grouped_collection_select :user_id, ProjectRole.order(:name), :users, :name, :id, :f_name, include_blank: true %>
                  <%= f.hidden_field :job_id, value: @job.id %>
                  <%= f.submit %>
                <% end %>
        
          
            </div>

            <div class="tab-pane fade" id="s4">
              <table id='checkbooks' class='table table-bordered table-striped'>
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Budget</th>
                  <th>Cost to Date</th>
                  <th>Savings/Overrun</th>
                </tr>
              </thead>
              <tbody>
                <% @checkbooks.each do |checkbook| %> 
                <tr>
                  <td><%= checkbook.name %></td>
                  <td><%= checkbook.description %></td>
                  <td><%= checkbook.budget %></td>
                  <td><%= checkbook.cost_to_date %></td>
                  <td><%= checkbook.savings_overrun %></td>
                </tr>
                <% end %>
              </tbody>
              </table>
                <button class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            Add Checkbook
          </button>
            </div>

              <div class="tab-pane fade" id="s5">
              <table id='checkbooks' class='table table-bordered table-striped'>
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Budget</th>
                  <th>Cost to Date</th>
                  <th>Savings/Overrun</th>
                </tr>
              </thead>
              <tbody>
                <% @checkbooks.each do |checkbook| %> 
                <tr>
                  <td><%= checkbook.name %></td>
                  <td><%= checkbook.description %></td>
                  <td><%= checkbook.budget %></td>
                  <td><%= checkbook.cost_to_date %></td>
                  <td><%= checkbook.savings_overrun %></td>
                </tr>
                <% end %>
              </tbody>
              </table>
                <button class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            Add Checkbook
          </button>
            </div>

          </div>
      
        </div>
        <!-- end widget content -->

      </div>
      <!-- end widget div -->

    </div>
    <!-- end widget -->

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
              &times;
            </button>
            <h4 class="modal-title" id="myModalLabel">Add Checkbook</h4>
          </div>
          <%= form_for [@job, @checkbook], remote: true, authenticity_token: true do |f| %>
          <div class="modal-body">
            <div class="row">
              <div class="col-md-12">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
                <%= f.label :description %>
                <%= f.text_area :description, class: 'form-control' %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="well well-sm well-primary">
                    <div class="form-group">
                      <%= f.label :budget %>
                      <%= f.text_field :budget, class: 'form-control' %>
                    </div>
                
                    <div class="form-group">
                  
                      <%= f.hidden_field :job_id, value: @job.id %>
                      <%= f.submit "Submit", class: 'btn btn-primary' %>
                      <% end %>
                    </div>
                  </form>
                </div>
              </div>
            </div>
    
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
              Cancel
            </button>
            <button id="add-contact-button" type="button" class="btn btn-primary">
              Add Contact
            </button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
        
        


<%= link_to "Edit Job", edit_job_path, class: "btn btn-primary" %>
<%= form_for @job, :html => { :class => "button_to" } do |f| %>
  <%= f.hidden_field :update_type, :value => :assign_job_number %> <!--Made up -->
  <%= f.submit "Submit", :class => "link" %>
<% end %>