config/routes.rb
GAL::Application.routes.draw do
  resources :sachse_groups
  get "welcome/index"
  resources :jobs do
    resources :checkbooks
    resources :job_assignments
    resources :staff_assignments
    resources :dailys do
      resources :daily_notes
    end
  end
  resources :psr
  resources :contract_types
  resources :states
  resources :project_types
  resources :project_phases
  resources :companies do
    resources :contacts
  end
  devise_for :users
  root to: 'welcome#index'
end

app/models/checkbook.rb
class Checkbook < ActiveRecord::Base
  belongs_to :job
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :state
  belongs_to :company_type
  belongs_to :trade
  belongs_to :country
  
  has_many :specialties
  has_many :trades, through: :specialties
  has_many :employments
  has_many :contacts, through: :employments

  has_many :job_assignments
  has_many :jobs, through: :job_assignments
  has_many :daily_manpowers, through: :job_assignments
end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
  has_many :companies
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :company_department
  belongs_to :state
  belongs_to :country

  has_many :employments
  has_many :companies, through: :employments

  has_many :job_assignments
  has_many :jobs, through: :job_assignments
  has_many :daily_manpowers, through: :job_assignments
end

app/models/contract_type.rb
class ContractType < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :companies
end

app/models/daily.rb
class Daily < ActiveRecord::Base
  belongs_to :job
  belongs_to :user
  has_many :daily_notes
  has_many :daily_manpowers
  has_many :contacts, through: :job_assignments
  has_many :daily_equipments
end

app/models/daily_note.rb
class DailyNote < ActiveRecord::Base
  belongs_to :daily
end

app/models/employment.rb
class Employment < ActiveRecord::Base
  belongs_to :company
  belongs_to :contact

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :state
  belongs_to :country
  belongs_to :project_phase
  belongs_to :project_type
  belongs_to :sachse_group
  belongs_to :union
  belongs_to :contract_type

  accepts_nested_attributes_for :state

  has_many :staff_assignments
  has_many :project_roles, through: :staff_assignments

  has_many :job_assignments
  has_many :companies, through: :job_assignments
  has_many :contacts, through: :job_assignments

  has_many :checkbooks

  has_many :dailys

  validates :name, presence: true

  before_save :assign_job_number, on: [ :create, :update ]
  before_save :change_job_number, on: [ :update ]
  before_save :assign_precon_number, on: :create


  def superintendents
    array = []
    self.staff_assignments.each do |staff|
      array << staff.user.name if staff.project_role.name == "Superintendent"
    end
    array
  end

  protected



  def assign_precon_number
    if !self.precon_number?
      array = []
        j = Job.all
        j.each do |job|
            #Loop across all jobs and pull out those that have a job number, as well as check if the first two digits of that job number (the year) == the current year
            array << job.precon_number if job.precon_number? && Time.now.strftime("%y") == job.precon_number[0..1]
          end
          #add one to the count of the array (if the current year and job number year don't equal, then it must be a new year and the count starts at 0)
          a = array.count + 1
      y = Time.now.strftime("%y")
      t = 35
      c = a.to_s.rjust(3, '0')
      self.precon_number = "#{y}-#{t}-#{c}"
      
    end
  end

  def assign_job_number


    #Does the job not have a job # but have a Contract Type?
    if !self.number? && self.contract_type_id?
        #Create an empty array
        array = []
        j = Job.all
        j.each do |job|
          #Loop across all jobs and pull out those that have a job number, and also check to see if the job number's year == the current year
          array << job.number if job.number? && Time.now.strftime("%y") == job.number[0..1]
        end
        a = array.count + 1
        y = Time.now.strftime("%y")
        t = self.contract_type.number
        c = a.to_s.rjust(3, '0')
        self.number = "#{y}-#{t}-#{c}"
    end
  end

  def change_job_number
    #Check if the job has a contract ID
    if self.contract_type_id?
      n = self.number
      y = n[0..1]
      t = self.contract_type.number
      c = n[6..8]
      self.number = "#{y}-#{t}-#{c}"
    end
  end
end

app/models/project_role.rb
class ProjectRole < ActiveRecord::Base
  has_many :staff_assignments
  has_many :jobs, through: :staff_assignments

  has_many :role_assignments
  has_many :users, through: :role_assignments

end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
end

app/models/sachse_group.rb
class SachseGroup < ActiveRecord::Base
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  belongs_to :company
  belongs_to :trade
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :companies
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  has_many :specialties
  has_many :companies, through: :specialties
end

app/models/union.rb
class Union < ActiveRecord::Base
  has_many :companies
  has_many :jobs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :role_assignments
  has_many :project_roles, through: :role_assignments
  has_many :dailys



  def name
    if self.l_name
      self.f_name + " " + self.l_name
    else
      self.f_name
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  respond_to :html, :js
  def index
    @companies = Company.all

    respond_to do |format|
      format.html
      format.json { render json: @companies, root: false }
    end
  end

  def new
    @company = Company.new
    @states = State.all
  end

  def edit
    @company = Company.find(params[:id])
  end

  def show
    @company = Company.find(params[:id])
    @contact = Contact.new
    @state = State.all
  end

 def create
    #binding.pry
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

     @company = Company.find(params[:id])
      #binding.pry
      respond_to do |format|
        if @company.update_attributes(company_params)
          format.html { redirect_to @company, notice: 'company was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @company.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
        @company = Company.find(params[:id])
        @company.destroy

        respond_to do |format|
          format.html { redirect_to companies_url }
          format.json { head :no_content }
        end
      end
  private

  def company_params
      params.require(:company).permit(:name, :address, :city, :state_id, :country_id, :zip, :phone, :website, :company_type_id)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/daily_helper.rb
module DailyHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/nav_helper.rb
module NavHelper
  def job_nav_list_items
    # @job = Job.find(params[:id])
    @nav_list_items = [[job_checkbooks_path(@job), 'Checkbooks'], [job_dailys_path(@job), "Daily Logs"]]
  end
end

app/helpers/psr_helper.rb
module PsrHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for company do |f| %>
      <%= f.input :name, input_html: { class: 'form-control input-sm'} %>
      <%= f.input :address, input_html: { class: 'form-control input-sm'} %>
      <%= f.input :city, input_html: { class: 'form-control input-sm'} %>
      <%= f.association :state, input_html: { class: 'form-control input-sm'} %>
      <%= f.input :zip, input_html: { class: 'form-control input-sm'} %>
      <%= f.association :company_type, input_html: { class: 'form-control input-sm'} %>
      <%= f.submit "Save", input_html: { class: 'btn btn-success'} %>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>
<div class="row">
  <div class="col-sm-4">
    <%= render partial: 'form', locals: { company: @company } %>
  </div>
</div>

app/views/companies/index.html.erb
<h1>Companies</h1>

<div class="row">
  <div class="col-md-8">
    <% @companies.each do |company| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to company.name, company %>
          </h4>
          <small>
            <%= company.address %><br>
            <%= company.city %>, <%= company.state.name %> <%= company.zip %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
      <%= link_to "New Company", new_company_path, id: "new_company", class: 'btn btn-primary', remote: true %>
  </div>
</div>

app/views/companies/new.html.erb
<%= render partial: 'form', locals: { company: @company } %>

app/views/companies/new.js.erb
$('#new_company').hide().after('<%= j render("form") %>');

app/views/companies/show.html.erb
<table class='table table-bordered'>
  <tr>
    <td><b>Company Name</b></td>
    <td><%= best_in_place @company, :name %></td>
    <td><b>Address</b></td>
    <td><%= best_in_place @company, :address %></td>
  </tr>
  <tr>
    <td><b>City</b></td>
    <td><%= best_in_place @company, :city, :nil => "Click me to add content!" %></td>
    <td><b>State</b></td>
  </tr>
</table>





<%= link_to "New Contact", new_company_contact_path(@company), class: "btn btn-primary" %>
<%= link_to "Edit Company", edit_company_path, class: "btn btn-success" %>