config/routes.rb
GAL::Application.routes.draw do
  resources :sachse_groups
  get "welcome/index"
  resources :jobs do
    resources :checkbooks
    resources :job_assignments
    resources :staff_assignments
    resources :dailys do
      resources :daily_notes
    end
  end
  resources :psr
  resources :contract_types
  resources :states
  resources :project_types
  resources :project_phases
  resources :companies do
    resources :contacts
  end
  devise_for :users
  root to: 'welcome#index'
end

app/models/checkbook.rb
class Checkbook < ActiveRecord::Base
  belongs_to :job
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :state
  belongs_to :company_type
  belongs_to :trade
  belongs_to :country
  
  has_many :specialties
  has_many :trades, through: :specialties
  has_many :employments
  has_many :contacts, through: :employments

  has_many :job_assignments
  has_many :jobs, through: :job_assignments
  has_many :daily_manpowers, through: :job_assignments
end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
  has_many :companies
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :company_department
  belongs_to :state
  belongs_to :country

  has_many :employments
  has_many :companies, through: :employments

  has_many :job_assignments
  has_many :jobs, through: :job_assignments
  has_many :daily_manpowers, through: :job_assignments
end

app/models/contract_type.rb
class ContractType < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :companies
end

app/models/daily.rb
class Daily < ActiveRecord::Base
  belongs_to :job
  belongs_to :user
  has_many :daily_notes
  has_many :daily_manpowers
  has_many :contacts, through: :job_assignments
  has_many :daily_equipments
end

app/models/daily_note.rb
class DailyNote < ActiveRecord::Base
  belongs_to :daily
end

app/models/employment.rb
class Employment < ActiveRecord::Base
  belongs_to :company
  belongs_to :contact

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :state
  belongs_to :country
  belongs_to :project_phase
  belongs_to :project_type
  belongs_to :sachse_group
  belongs_to :union
  belongs_to :contract_type

  accepts_nested_attributes_for :state

  has_many :staff_assignments
  has_many :project_roles, through: :staff_assignments

  has_many :job_assignments
  has_many :companies, through: :job_assignments
  has_many :contacts, through: :job_assignments

  has_many :checkbooks

  has_many :dailys

  validates :name, presence: true

  before_save :assign_job_number, on: [ :create, :update ]
  before_save :change_job_number, on: [ :update ]
  before_save :assign_precon_number, on: :create


  def superintendents
    array = []
    self.staff_assignments.each do |staff|
      array << staff.user.name if staff.project_role.name == "Superintendent"
    end
    array
  end

  protected



  def assign_precon_number
    if !self.precon_number?
      array = []
        j = Job.all
        j.each do |job|
            #Loop across all jobs and pull out those that have a job number, as well as check if the first two digits of that job number (the year) == the current year
            array << job.precon_number if job.precon_number? && Time.now.strftime("%y") == job.precon_number[0..1]
          end
          #add one to the count of the array (if the current year and job number year don't equal, then it must be a new year and the count starts at 0)
          a = array.count + 1
      y = Time.now.strftime("%y")
      t = 35
      c = a.to_s.rjust(3, '0')
      self.precon_number = "#{y}-#{t}-#{c}"
      
    end
  end

  def assign_job_number


    #Does the job not have a job # but have a Contract Type?
    if !self.number? && self.contract_type_id?
        #Create an empty array
        array = []
        j = Job.all
        j.each do |job|
          #Loop across all jobs and pull out those that have a job number, and also check to see if the job number's year == the current year
          array << job.number if job.number? && Time.now.strftime("%y") == job.number[0..1]
        end
        a = array.count + 1
        y = Time.now.strftime("%y")
        t = self.contract_type.number
        c = a.to_s.rjust(3, '0')
        self.number = "#{y}-#{t}-#{c}"
    end
  end

  def change_job_number
    #Check if the job has a contract ID
    if self.contract_type_id?
      n = self.number
      y = n[0..1]
      t = self.contract_type.number
      c = n[6..8]
      self.number = "#{y}-#{t}-#{c}"
    end
  end
end

app/models/project_role.rb
class ProjectRole < ActiveRecord::Base
  has_many :staff_assignments
  has_many :jobs, through: :staff_assignments

  has_many :role_assignments
  has_many :users, through: :role_assignments

end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
end

app/models/sachse_group.rb
class SachseGroup < ActiveRecord::Base
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  belongs_to :company
  belongs_to :trade
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :companies
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  has_many :specialties
  has_many :companies, through: :specialties
end

app/models/union.rb
class Union < ActiveRecord::Base
  has_many :companies
  has_many :jobs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :role_assignments
  has_many :project_roles, through: :role_assignments
  has_many :dailys



  def name
    if self.l_name
      self.f_name + " " + self.l_name
    else
      self.f_name
    end
  end
end

app/controllers/dailys_controller.rb
class DailysController < ApplicationController
  include NavHelper
  def index
    # binding.pry
    @job = Job.find(params[:job_id])
    @dailys = @job.dailys
    @daily = Daily.new
    @nav_list_items = job_nav_list_items
    respond_to do |format|
      format.html
      format.json { render json: @dailys, root: false }
    end
  end

  def new
    @job = Job.find(params[:job_id])
    @daily = Daily.new
  end

  def edit
    @job = Job.find(params[:job_id])
    @daily = @job.daily.find(params[:id])
  end

  def show
    @job = Job.find(params[:job_id])
    @daily = @job.dailys.find(params[:id])
    @daily_note = DailyNote.new
    @daily_notes = @daily.daily_notes
    @dailys = @job.dailys

    

  end

  def create
    #binding.pry
    @job = Job.find(params[:job_id])
    @daily = current_user.dailys.build(daily_params)
    @daily.job = @job
    if @daily.save
      flash[:notice] = "Daily Log was successfully added"

      respond_to do |format|
        format.html {redirect_to @daily.job}
        format.js { render :create }
      end
    end
  end

  def update
    @job = Job.find(params[:id])    
    @daily = Daily.find(params[:id])
  #binding.pry
    if @daily.update_attributes(daily_params)
      format.html { redirect_to @daily.job, notice: 'Daily Log was successfully updated.' }
      
    else
      format.html { render action: "edit" }
      
    end
  end

  def destroy
    @job = Job.find(params[:job_id])
    @daily = Daily.find(params[:id])
    @daily.destroy

    respond_to do |format|
      format.html { redirect_to @job }
      format.js { render :destroy }
    end
  end

private

  def daily_params
      params.require(:daily).permit(:job_id, :date, :user_id, :am_temp, :pm_temp, :weather_desc, :notes)
  end

end

app/helpers/daily_helper.rb
module DailyHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/nav_helper.rb
module NavHelper
  def job_nav_list_items
    # @job = Job.find(params[:id])
    @nav_list_items = [[job_checkbooks_path(@job), 'Checkbooks'], [job_dailys_path(@job), "Daily Logs"]]
  end
end

app/helpers/psr_helper.rb
module PsrHelper
end

app/views/dailys/create.js.erb
var rowTemplate = "<tr><td><%= @daily.date %></td><td><%= @daily.am_temp %></td><td><%= @daily.pm_temp %></td><td><%= @daily.weather_desc %></td><td><%= @daily.notes %></td><td></td</tr>"

$(".new-log").prepend(rowTemplate);

app/views/dailys/index.html.erb
<h1>Daily Logs</h1>
<% @dailys.each do |daily| %>
  <p><%= link_to daily.date ,job_daily_path(@job, daily) %></p>
  <% end %>

app/views/dailys/show.html.erb
<div class="well">
  <h3>Notes Log</h3>
  <h5>Select Date</h5>
  <div id="example">
    <input id="datepicker">
  </div>
  <%= form_for [@job, @daily, @daily_note], remote: true, authenticity_token: true do |f| %>
  <%= f.collection_select :daily_id, @job.dailys.order(:date), :id, :date, include_blank: true %>
  <% end %>


  <!-- possibly add url as a data attribute to each option -->
  <!-- on click, use the AJAX load method to replace the contents of the page -->
    <table id='daily-notes' class='table table-bordered table-striped'>
      <thead>
        <tr>
          <th>No.</th>
          <th>Issue?</th>
          <th>Location</th>
          <th>Comment</th>
          <th>Attachments</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @daily_notes.each do |daily| %> 
          <tr>
            <td></td>
            <td><%= check_box_tag :issue %></td>
            <td><%= daily.location %></td>
            <td><%= daily.comment %></td>
            <td></td>
          </tr>
      <% end %>
      <%= form_for [@job, @daily, @daily_note], remote: true, authenticity_token: true do |f| %>
      <tr class: 'new-log'>
        <td></td>
        <td><%= f.check_box :issue, class: 'form-control input-xs' %></td>
        <td><%= f.text_field :location, class: 'form-control', placeholder: 'Enter location'%></td>
        <td><%= f.text_area :comment, class: 'form-control', placeholder: 'Notes'%></td>
        <%= f.hidden_field :daily_id, value: @daily.id %>

        <td><%= f.submit "Add" %>
      </tr>
        <% end %>
    </tbody>
    </table>

  </div>
</div>

<%= javascript_tag do %>
<!--   window.jobs = <%=raw @jobs %>; -->
  window.job = "<%=raw @job.id %>";
<% end %>

app/views/dailys/show.json.erb
{
    "hello": "world"
}